repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.0
  hooks:
    # # Run the linter (disabled for now, as we're just looking at formatting)
    # - id: ruff
    #  args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=1200']
    - id: check-case-conflict
    - id: mixed-line-ending
    - id: trailing-whitespace
    # - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-merge-conflict
