#
# YAML file configuring the actions to take when releasing to production
#
# > Syntax tips here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Pull request checker

on:
  pull_request

jobs:
  check_pull_request:
    name: check pull request

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Create UV installation"
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.9.2"

      # Check and fix the code
      - name: Defining Git identity
        run: |
          git config user.name github_actions
          git config user.email github_actions@opensustain.tech

      - name: Run code cleanup
        run: |
          make cleanup || echo "Precommits modified the files"

      - name: Commit changes back
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github_actions
          message: "Automatic code reformatting"
          add: "."
          push: true
